### ISSUE TITLE
Reminder Time

### ISSUE THREAD

**Issue by YoussefMohamed47** [hadywalied/Zakker#1]
Need to know the reminder of the zakker will work , meaning that how often it will show to me while coding as hint or small popup (Periodic Time) of zakker?

**Comment by hadywalied** [comment]
I'm working on making it configurable in plugin settings, that'll be in the December release insha'Allah.

Currently I'm working on a Visual studio code port of the plugin.

**Comment by YoussefMohamed47** [comment]
insha'Allah
